DROP TABLE user_roles IF EXISTS;
DROP TABLE users IF EXISTS;
DROP TABLE dishes IF EXISTS;
DROP TABLE restaurants IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE global_seq AS INTEGER START WITH 100000;

CREATE TABLE restaurants
(
  id                INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
  name             VARCHAR(255)             NOT NULL,
  count_of_votes    INTEGER DEFAULT 0        NOT NULL
);
CREATE UNIQUE INDEX restaurants_unique_name_idx ON restaurants (name);

CREATE TABLE dishes
(
  id                INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
  name             VARCHAR(255)        NOT NULL,
  price             INTEGER              NOT NULL,
  date             DATE                  NOT NULL,
  restaurant_id     INTEGER              NOT NULL,
  FOREIGN KEY (restaurant_id) REFERENCES restaurants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX dishes_unique_restaurant_name_date_idx ON dishes (restaurant_id, name, date);

CREATE TABLE users
(
  id                INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
  name              VARCHAR(255)               NOT NULL,
  email              VARCHAR(255)               NOT NULL,
  password          VARCHAR(255)               NOT NULL,
  restaurant_id      INTEGER,
  FOREIGN KEY (restaurant_id) REFERENCES restaurants (id)
);
CREATE UNIQUE INDEX users_unique_email_idx ON users (email);

CREATE TABLE user_roles
(
  user_id INTEGER NOT NULL,
  role    VARCHAR(255),
  CONSTRAINT user_roles_idx UNIQUE (user_id, role),
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);